### ISSUE TITLE
Write Learn Godot: developers edition

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/GDquest-website#94]
Write a curated guide for professional developers to learn Godot with free resources. This guide aggregates quality resources and gives the reader a path to learn to switch to Godot.

**Target audience**: professional developers, people working in the game industry or not, using another game engine.

This guide should only contain free resources. The idea is to have high quality and relevant content to **link to**, video or text. We're going to use it to direct people to great content around Godot.

The guide should be:

1. **engaging**, the goal is to help people learn and keep going.
1. **curated**, we should stick to high quality content.
1. **structured**, it should provide clear sections, goals, and milestones.

## Goal

The guide should provide experienced game developers with the resources to make sense of Godot, know where to find resources, and get up to speed quickly.

Once it is done, the guide will be open to Contributors. As such we should also have some guidelines regarding the type of content that can be included.

Keep it short. This will be a living guide, hopefully maintained by the community.

## Tasks

1. [ ] Write an outline for the guide. See #80 for reference
2. [ ] Collect relevant resources to include in the guide
3. [ ] Write the actual guide in markdown
